version: 2.1

executors:
  build-executor:
    docker:
      - image: cimg/openjdk:11.0.16
        environment:
          MAVEN_OPTS: -Xmx1g

workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: Compile source with tests
          command: |
            make
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - run:
          name: Collect artifacts
          command: |
            mkdir -p ~/artifacts/
            find . -type f -regex ".*\/assembly\/kar\/target\/opennms-pagerduty-plugin-.*\.kar" -exec cp {} ~/artifacts/ \;
      - run:
          name: Create archive with checksums
          command: |
            cd ~/artifacts
            shasum -a 256 -b opennms-pagerduty-plugin-*.kar > shasum256.txt
            tar czf opennms-pagerduty-plugin.tar.gz opennms-pagerduty-plugin-*.kar shasum256.txt
            shasum -a 256 -b opennms-pagerduty-plugin.tar.gz > opennms-pagerduty-plugin.sha256
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/artifacts
