---
version: 2.1

executors:
  build-executor:
    docker:
      - image: cimg/openjdk:17.0.14
        environment:
          MAVEN_OPTS: -Xmx1g
  go-executor:
    docker:
      - image: cimg/go:1.23

workflows:
  build-deploy:
    jobs:
      - build
      - publish-github-release:
          context:
            - github-releases
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: Compile source with tests
          command: make
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - run:
          name: Collect artifacts
          command: make collect-artifacts
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: target/artifacts
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  publish-github-release:
    executor: go-executor
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install ghr tool to create GitHub releases and upload artifacts
          command: go install github.com/tcnksm/ghr@latest
      - run:
          name: Publish artifacts as GitHub release
          command: |
            export GITHUB_TOKEN="${GH_TOKEN}"
            mkdir github-release
            cp target/artifacts/opennms-pagerduty-plugin.sha256 github-release
            cp target/artifacts/opennms-pagerduty-plugin.tar.gz github-release
            ghr -r ${CIRCLE_PROJECT_REPONAME} $(cat target/artifacts/pom-version.txt) github-release
