---
name: pagerduty-plugin-build
run-name: Build and run test suites for the PagerDuty plugin
on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*.*.*'
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compile source without tests
        run: |
          make
      - name: Persist Karaf archive
        uses: actions/upload-artifact@v4
        with:
          name: kar-file
          path: assembly/kar/target/opennms-pagerduty-plugin-*.kar
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: kar-file
      - name: Generate KAR file checksum
        run: shasum -a 256 -b opennms-pagerduty-plugin-*.kar > shasum256.txt
      - name: Create release archive
        run: tar czf opennms-pagerduty-plugin.tar.gz opennms-pagerduty-plugin-*.kar shasum256.txt
      - name: Generate tar.gz checksum
        run: shasum -a 256 -b opennms-pagerduty-plugin.tar.gz > opennms-pagerduty-plugin.sha256
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          make_latest: true
          generate_release_notes: true
          files: |
            *.tar.gz
            *.sha256
